services:
  web:
    image: caddy:alpine
    container_name: caddy
    ports:
      - "3002:80"
    volumes:
      - .:/srv/www/ewancroft.uk
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
    networks:
      - www
    depends_on:
      - php-fpm

  php-fpm:
    image: php:7.4-fpm-alpine
    container_name: php-fpm
    volumes:
      - .:/srv/www/ewancroft.uk
    networks:
      - www

networks:
  www:
    external: false
