services:
  web:
    build: .
    container_name: ewancroft-web
    ports:
      - "3002:3000"
    networks:
      - www
    environment:
      - NODE_ENV=production

networks:
  www:
    external: false