services:
  web:
    image: caddy:alpine
    ports:
      - "3002:80"
    volumes:
      - .:/srv/www/ewancroft.uk
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
    networks:
      - www

networks:
  www:
    external: true